management:
  security:
    enabled: false
application:
  staff-simulator:
    infra:
      preparation:
        base-url: http://localhost:8080/preparation
        cron: "*/30 * * * * *"
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"