version: '3.8'

services:
  database:
    build: ./database
    environment:
      POSTGRES_DB: handson
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    ports:
      - published: 5432
        target: 5432

  modular-monolith:
    build: ./modular-monolith
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/handson?schema=handson
    ports:
      - published: 8080
        target: 8080
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
