management:
  security:
    enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/handson?schema=handson
    username: user
    password: user123
application:
  ordering:
    infra:
      menu:
        base-url: http://localhost:8080/menu
      preparation:
        base-url: http://localhost:8080/preparation
      stock:
        base-url: http://localhost:8080/stock
  preparation:
    infra:
      stock:
        base-url: http://localhost:8080/stock
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
